models:
  - name: gpt-3.5-turbo
    type: chat
    provider: OpenAI
    temperature: 0.7
    streaming: true
    default: true

  - name: gpt-4
    type: chat
    provider: OpenAI
    temperature: 0.7
    streaming: true

  - name: gemini-pro
    type: chat
    provider: Google
    temperature: 0.7
    streaming: true

  - name: llama-2-70b-chat
    type: chat
    provider: Replicate
    temperature: 0.7
    streaming: true

  - name: mixtral-8x7b
    type: chat
    provider: Replicate
    temperature: 0.7
    streaming: true 