name: Summarizer
description: Summarizes text input using LangChain
input_type: text
output_type: text
parameters:
  - name: max_length
    type: int
    default: 150
  - name: chain_type
    type: str
    default: "stuff" 